### ISSUE TITLE
run emulator failed, nested virtualization is not supported

### ISSUE THREAD

**Issue by Eugene-Novikov** [fastphat/android-container#33]
Hello, thanks a lot for example!
Could you please help to find issue?

I'm running it on jenkins (CentOS Linux), but faced with the same error as on Windows and OSX (run emulator failed, nested virtualization is not supported)
More details about OS and CPU and all logs in the attached file.

Thanks in advance.
[jenkins pipeline result.txt](https://github.com/phatnhse/android-container/files/8305157/jenkins.pipeline.result.txt)

**Comment by phatnhse** [comment]
MacOS/Window or any solution which uses VirtualBox to embed Docker can't run x86 emulator because [nested virtualization](https://www.virtualbox.org/ticket/4032) is currently not supported.

I did check your txt file but thing seems normal, can you help me to specify or give me more details about the issue that you're having?

**Comment by Eugene-Novikov** [comment]
yes, sure
run emulator failed, nested virtualization is not supported (in the jenkins log)

cpu_support_hardware_acceleration=$(grep -cw ".*\(vmx\|svm\).*" /proc/cpuinfo)
returns 0

Plus such log during building image:
* If you want to run VM as unprivileged user and let Qemu create tunX devices,
* then you must add that user to the group "qemu".
* If you use KVM for hardware-assisted virtualization, then you may also need
* to add that user to the group "kvm".
